root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/server ."
bin = "tmp/server"
full_bin = "tmp/server"
include_ext = ["go"]
exclude_dir = ["assets", "tmp", "vendor", "testdata", "go"]

[log]
time = true
